update build-n-publish workflow to build repo with pyproject.toml file

diff --git a/.github/workflows/release_to_pypi.yml b/.github/workflows/release_to_pypi.yml
--- a/.github/workflows/release_to_pypi.yml
+++ b/.github/workflows/release_to_pypi.yml
@@ -20,7 +20,7 @@ jobs:
         - name: Set up Python
           uses: actions/setup-python@v4.3.0
           with:
-            python-version: "3.9"
+            python-version: "3.13"
 
         - name: Install dependencies
           run: |
@@ -32,7 +32,20 @@ jobs:
 
         - name: Build source and wheel distributions
           run: |
-            python setup.py sdist bdist_wheel
+            if [ -d "dist" ]; then
+              rm -rf dist
+            fi
+            if [ -f "./setup.py" ]; then
+              python setup.py sdist bdist_wheel
+            elif [ -f "./pyproject.toml" ]; then
+              if [ -f "./genpackagedoc.py" ]; then
+                python genpackagedoc.py
+              fi
+              python -m build
+            else
+              echo "Error: No setup.py or pyproject.toml found for building the package."
+              exit 1
+            fi
             twine check --strict dist/*
 
         - name: Publish distribution to PyPI
